return {
  alias = { "laias", "alais" },
  coproc = { "ocproc", "corpoc", "coporc", "coprco" },
  ["do"] = { "od" },
  done = { "odne", "doen" },
  echo = { "ehco" },
  elif = { "leif", "elfi" },
  ["else"] = { "lese", "esle" },
  eval = { "evla" },
  export = { "epxort", "exprot" },
  ["for"] = { "ofr", "fro" },
  ["function"] = { "ufnction", "fucntion", "funciton" },
  jobs = { "jbos" },
  printf = { "rpintf", "pirntf", "pritnf" },
  pwd = { "wpd" },
  select = { "sleect", "seelct" },
  shift = { "hsift", "shfit" },
  source = { "osurce", "soruce" },
  ["then"] = { "hten", "tehn", "thne" },
  time = { "itme", "tiem" },
  trap = { "trpa" },
  type = { "ytpe", "tyep" },
  unset = { "usnet" },
  ["until"] = { "utnil", "unitl" },
  wait = { "wiat", "wati" },
  ["while"] = { "hwile", "whiel" },
}
