return {
  ["break"] = { "breka" },
  chan = { "hcan", "cahn", "chna" },
  const = { "ocnst", "cosnt" },
  continue = { "ocntinue", "cotninue", "conitnue", "contineu" },
  default = { "defualt", "defautl" },
  ["else"] = { "lese", "esle" },
  fallthrough = {
    "flalthrough",
    "faltlhrough",
    "fallhtrough",
    "falltrhough",
    "fallthorugh",
    "fallthroguh",
    "fallthrouhg",
  },
  ["for"] = { "ofr", "fro" },
  func = { "ufnc", "fucn" },
  go = { "og" },
  ["goto"] = { "ogto", "gtoo", "goot" },
  ["if"] = { "fi" },
  import = { "improt" },
  interface = { "itnerface" },
  map = { "amp", "mpa" },
  package = { "apckage", "pakcage", "pacakge" },
  range = { "rnage", "ragne" },
  ["return"] = { "reutrn", "retrun", "retunr" },
  select = { "sleect", "seelct" },
  struct = { "sturct", "strcut" },
  switch = { "siwtch", "swtich", "swithc" },
  type = { "ytpe", "tyep" },
}
