--- here the table for us lua should be returned (from expected_mixups.lua file)
return {
  ["and"] = { "nad", "adn" },
  ["break"] = { "breka" },
  ["do"] = { "od" },
  ["else"] = { "lese", "esle" },
  ["elseif"] = { "leseif", "esleif", "elsief", "elsefi" },
  ["end"] = { "ned", "edn" },
  ["false"] = { "flase", "fasle" },
  ["for"] = { "ofr", "fro" },
  ["function"] = { "ufnction", "fucntion", "funciton" },
  ["if"] = { "fi" },
  ["local"] = { "lcoal", "locla" },
  ["not"] = { "nto" },
  ["or"] = { "ro" },
  ["repeat"] = { "rpeeat", "reepat" },
  ["return"] = { "reutrn", "retrun", "retunr" },
  ["then"] = { "hten", "tehn", "thne" },
  ["true"] = { "ture", "treu" },
  ["until"] = { "utnil", "unitl" },
  ["while"] = { "hwile", "whiel" },
}
