return {
  alias = { "laias", "alais" },
  ascending = { "ascneding", "ascedning", "ascenidng", "ascendign" },
  async = { "asnyc", "asycn" },
  await = { "awiat", "awati" },
  descending = { "descneding", "descedning", "descenidng", "descendign" },
  dynamic = { "dnyamic", "dyanmic", "dynmaic", "dynamci" },
  equals = { "euqals", "eqauls", "equlas", "equasl" },
  from = { "form" },
  global = { "lgobal", "glboal", "globla" },
  group = { "gorup" },
  into = { "itno", "inot" },
  let = { "elt" },
  nameof = { "anmeof", "nmaeof", "naemof", "namoef", "namefo" },
  orderby = { "roderby" },
  partial = { "aprtial", "parital", "partail", "partila" },
  remove = { "rmeove", "remvoe" },
  select = { "sleect", "seelct" },
  value = { "vlaue", "valeu" },
  when = { "hwen", "wehn", "whne" },
  where = { "hwere", "wehre" },
  yield = { "iyeld", "yeild", "yiled", "yiedl" },
}
