return {
  us = {
    c = require("tests.syntax-hand-fix.expectations.us.c"),
    cpp = require("tests.syntax-hand-fix.expectations.us.cpp"),
    csharp = require("tests.syntax-hand-fix.expectations.us.csharp"),
    go = require("tests.syntax-hand-fix.expectations.us.go"),
    haskell = require("tests.syntax-hand-fix.expectations.us.haskell"),
    html = require("tests.syntax-hand-fix.expectations.us.html"),
    java = require("tests.syntax-hand-fix.expectations.us.java"),
    javascript = require("tests.syntax-hand-fix.expectations.us.javascript"),
    kotlin = require("tests.syntax-hand-fix.expectations.us.kotlin"),
    lua = require("tests.syntax-hand-fix.expectations.us.lua"),
    php = require("tests.syntax-hand-fix.expectations.us.php"),
    python = require("tests.syntax-hand-fix.expectations.us.python"),
    ruby = require("tests.syntax-hand-fix.expectations.us.ruby"),
    rust = require("tests.syntax-hand-fix.expectations.us.rust"),
    scala = require("tests.syntax-hand-fix.expectations.us.scala"),
    swift = require("tests.syntax-hand-fix.expectations.us.swift"),
    typescript = require("tests.syntax-hand-fix.expectations.us.typescript"),
  },
  de = {
    c = require("tests.syntax-hand-fix.expectations.de.c"),
    cpp = require("tests.syntax-hand-fix.expectations.de.cpp"),
    csharp = require("tests.syntax-hand-fix.expectations.de.csharp"),
    go = require("tests.syntax-hand-fix.expectations.de.go"),
    haskell = require("tests.syntax-hand-fix.expectations.de.haskell"),
    html = require("tests.syntax-hand-fix.expectations.de.html"),
    java = require("tests.syntax-hand-fix.expectations.de.java"),
    javascript = require("tests.syntax-hand-fix.expectations.de.javascript"),
    kotlin = require("tests.syntax-hand-fix.expectations.de.kotlin"),
    lua = require("tests.syntax-hand-fix.expectations.de.lua"),
    php = require("tests.syntax-hand-fix.expectations.de.php"),
    python = require("tests.syntax-hand-fix.expectations.de.python"),
    ruby = require("tests.syntax-hand-fix.expectations.de.ruby"),
    rust = require("tests.syntax-hand-fix.expectations.de.rust"),
    scala = require("tests.syntax-hand-fix.expectations.de.scala"),
    swift = require("tests.syntax-hand-fix.expectations.de.swift"),
    typescript = require("tests.syntax-hand-fix.expectations.de.typescript"),
  },
}
